
[GLOBAL]
DEVICE = cuda
SEED = 42
AGENT = a2c

[ENVIRONMENT]
NAME = Pendulum-v0
N_ENVS = 16
ACTION_SIZE = 1
ACTION_SPACE = continuous
ACTION_RANGE = -2, 2
STATE_SIZE = 3

[A2C]

  [[ACTOR]]
  ARCHITECTURE = fc
  HIDDEN_SIZE = 16,
  LR = 0.0008
  WEIGHT_DECAY = 0.0
  OPTIMIZER = adam
  OUTPUT_LOC_SCALER = 2

  [[CRITIC]]
  ARCHITECTURE = fc
  HIDDEN_SIZE = 32,
  LR = 0.0005
  WEIGHT_DECAY = 0.01
  OPTIMIZER = adam

  [[TRAINING]]
  GAMMA = 0.99
  N_STEP_BS = 4
  GRADIENT_CLIP = 5.

[EXPLORATION]
TYPE = gaussian
SIZE = 1
EPS_BETA = 0.1
EPS_MIN = 0.01
MEAN = 0.0
SIGMA = 0.1
THETA = 0.01

[TRAINER]
ENTROPY_WEIGHT = 0.01
MAX_STEPS = 200
EPISODES = 1000
PRINT_EVERY =  10
DEQUE_LEN = 50
UPDATE_EVERY = 1
