
[GLOBAL]
DEVICE = cuda
SEED = 42
AGENT = a2c

[ENVIRONMENT]
NAME = Pendulum-v0
N_ENVS = 20
ACTION_SIZE = 1
ACTION_SPACE = continuous
ACTION_RANGE = -2, 2
STATE_SIZE = 3

[A2C]

  [[ACTOR]]
  ARCHITECTURE = fc
  HIDDEN_SIZE = 256, 128
  LR = 0.0005
  WEIGHT_DECAY = 0.0
  OPTIMIZER = adam

  [[CRITIC]]
  ARCHITECTURE = fc
  HIDDEN_SIZE = 256, 128
  LR = 0.0005
  WEIGHT_DECAY = 1.0e-05
  OPTIMIZER = adam

  [[TRAINING]]
  GAMMA = 0.99
  N_STEP_BS = 5

[EXPLORATION]
TYPE = gaussian
SIZE = 1
EPS_BETA = 0.1
EPS_MIN = 0.01
MEAN = 0.0
SIGMA = 0.2
THETA = 0.01

[TRAINER]
MAX_STEPS = 200
EPISODES = 1000
PRINT_EVERY =  100
UPDATE_EVERY = 5
