[TRAINING]
AGENT: a2c
DEVICE: cuda
BATCH_SIZE: 256
BUFFER_SIZE: 1000000
MAX_T: 2000
N_AGENTS: 2
EPISODES: 2000
PRINT_EVERY: 100
SEED: 42
SUCCESS_SCORE: 0.5
UPDATE_EVERY: 1
WANDB: True

[EXPLORATION]
# Type of exploration used
NOISE: gaussian
# TODO
EPS_BETA: 0.1
EPS_MIN: 0.01
MEAN: 0.0
SIGMA: 0.4
THETA: 0.01

[AGENT]
ACTION_SIZE: 2
STATE_SIZE: 24
ACTOR_GRADIENT_CLIP_VALUE: 5
ACTOR_LR: 0.001
ACTOR_WEIGHT_DECAY: 0.0
CRITIC_GRADIENT_CLIP_VALUE: 1
CRITIC_LR: 0.001
CRITIC_WEIGHT_DECAY: 1.0e-05
GAMMA: 0.99
TAU: 0.005
SEED: 42
