[TRAINING]
SEED = 42
DEVICE = cuda
BATCH_SIZE = 256
BUFFER_SIZE = 1000000
MAX_T = 2000
N_AGENTS= 2
EPISODES = 2000
PRINT_EVERY = 100
SUCCESS_SCORE = 0.5
UPDATE_EVERY = 1
WANDB = True

[AGENT]
TYPE = a2c
ACTION_SIZE = 2
STATE_SIZE = 24
GAMMA = 0.99
TAU = 0.005

  [[ACTOR]]
  HIDDEN_SIZE = 256, 32
  GRADIENT_CLIP_VALUE = 5
  LR = 0.001
  WEIGHT_DECAY = 0.0
  OPTIMIZER = adam

  [[CRITIC]]
  HIDDEN_SIZE = 256, 128
  GRADIENT_CLIP_VALUE = 1
  LR = 0.001
  WEIGHT_DECAY = 1.0e-05
  OPTIMIZER = adam

[EXPLORATION]
TYPE = gaussian
SIZE = 2
EPS_BETA = 0.1
EPS_MIN = 0.01
MEAN = 0.0
SIGMA = 0.4
THETA = 0.01
